### ISSUE TITLE
I can't run zonation

### ISSUE THREAD

**Issue by jgomezd** [wkmor1/rzonation#2]
Dear developers,

I am trying to run zonation. There characteristics of my operative system are:
Windows 64 bits
Intel Core i7

my R version is 3.5.3

I run the following code:
library(rzonation)
r1 <- raster(matrix(runif(200^2, 0, 1), 200))
r2 <- raster(matrix(runif(200^2, 0, 1), 200))

plan <- zonation(stack(r1, r2))

I have the following message:
Error in zonation(features = feature_files, params, settings, dir, alpha,  : 
  zonation binary not found

Could you please indicate me how can I proceed?
Best regards,

Jorge

**Comment by wkmor1** [comment]
Hi Jorge. Looks like you might have not installed zonation yet. https://github.com/cbig/zonation-core/releases
